import { Stock } from '@/types/stock';

export const LQ45_STOCKS: Stock[] = [
  { symbol: 'BBCA.JK', name: 'Bank Central Asia Tbk', sector: 'Finance' },
  { symbol: 'BBRI.JK', name: 'Bank Rakyat Indonesia Tbk', sector: 'Finance' },
  { symbol: 'BMRI.JK', name: 'Bank Mandiri Tbk', sector: 'Finance' },
  { symbol: 'BBNI.JK', name: 'Bank Negara Indonesia Tbk', sector: 'Finance' },
  { symbol: 'TLKM.JK', name: 'Telkom Indonesia Tbk', sector: 'Telecommunication' },
  { symbol: 'ASII.JK', name: 'Astra International Tbk', sector: 'Automotive' },
  { symbol: 'UNVR.JK', name: 'Unilever Indonesia Tbk', sector: 'Consumer Goods' },
  { symbol: 'GOTO.JK', name: 'GoTo Gojek Tokopedia Tbk', sector: 'Technology' },
  { symbol: 'AMMN.JK', name: 'Amman Mineral Internasional Tbk', sector: 'Mining' },
  { symbol: 'ANTM.JK', name: 'Aneka Tambang Tbk', sector: 'Mining' },
  { symbol: 'INDF.JK', name: 'Indofood Sukses Makmur Tbk', sector: 'Consumer Goods' },
  { symbol: 'ICBP.JK', name: 'Indofood CBP Sukses Makmur Tbk', sector: 'Consumer Goods' },
  { symbol: 'KLBF.JK', name: 'Kalbe Farma Tbk', sector: 'Healthcare' },
  { symbol: 'EMTK.JK', name: 'Elang Mahkota Teknologi Tbk', sector: 'Media' },
  { symbol: 'ADRO.JK', name: 'Adaro Energy Indonesia Tbk', sector: 'Mining' },
  { symbol: 'PTBA.JK', name: 'Bukit Asam Tbk', sector: 'Mining' },
  { symbol: 'INKP.JK', name: 'Indah Kiat Pulp & Paper Tbk', sector: 'Manufacturing' },
  { symbol: 'SMGR.JK', name: 'Semen Indonesia Tbk', sector: 'Construction' },
  { symbol: 'INTP.JK', name: 'Indocement Tunggal Prakarsa Tbk', sector: 'Construction' },
  { symbol: 'GGRM.JK', name: 'Gudang Garam Tbk', sector: 'Consumer Goods' },
  { symbol: 'HMSP.JK', name: 'HM Sampoerna Tbk', sector: 'Consumer Goods' },
  { symbol: 'BRIS.JK', name: 'Bank BRI Syariah Tbk', sector: 'Finance' },
  { symbol: 'EXCL.JK', name: 'XL Axiata Tbk', sector: 'Telecommunication' },
  { symbol: 'PGAS.JK', name: 'Perusahaan Gas Negara Tbk', sector: 'Energy' },
  { symbol: 'PWON.JK', name: 'Pakuwon Jati Tbk', sector: 'Property' },
  { symbol: 'MNCN.JK', name: 'Media Nusantara Citra Tbk', sector: 'Media' },
  { symbol: 'AKRA.JK', name: 'AKR Corporindo Tbk', sector: 'Trade' },
  { symbol: 'CPIN.JK', name: 'Charoen Pokphand Indonesia Tbk', sector: 'Agriculture' },
  { symbol: 'BRPT.JK', name: 'Barito Pacific Tbk', sector: 'Chemical' },
  { symbol: 'ITMG.JK', name: 'Indo Tambangraya Megah Tbk', sector: 'Mining' },
  { symbol: 'MEDC.JK', name: 'Medco Energi Internasional Tbk', sector: 'Energy' },
  { symbol: 'SCMA.JK', name: 'Surya Citra Media Tbk', sector: 'Media' },
  { symbol: 'MAPI.JK', name: 'Mitra Adiperkasa Tbk', sector: 'Retail' },
  { symbol: 'JSMR.JK', name: 'Jasa Marga Tbk', sector: 'Infrastructure' },
  { symbol: 'WIKA.JK', name: 'Wijaya Karya Tbk', sector: 'Construction' },
  { symbol: 'WSKT.JK', name: 'Waskita Karya Tbk', sector: 'Construction' },
  { symbol: 'PTPP.JK', name: 'PP Tbk', sector: 'Construction' },
  { symbol: 'TPIA.JK', name: 'Chandra Asri Pacific Tbk', sector: 'Chemical' },
  { symbol: 'UNTR.JK', name: 'United Tractors Tbk', sector: 'Automotive' },
  { symbol: 'TOWR.JK', name: 'Sarana Menara Nusantara Tbk', sector: 'Telecommunication' },
  { symbol: 'ERAA.JK', name: 'Erajaya Swasembada Tbk', sector: 'Retail' },
  { symbol: 'BSDE.JK', name: 'Bumi Serpong Damai Tbk', sector: 'Property' },
  { symbol: 'JPFA.JK', name: 'Japfa Comfeed Indonesia Tbk', sector: 'Agriculture' },
  { symbol: 'ACES.JK', name: 'Ace Hardware Indonesia Tbk', sector: 'Retail' },
  { symbol: 'SIDO.JK', name: 'Industri Jamu Dan Farmasi Sido Muncul Tbk', sector: 'Healthcare' },
];

export const OTHER_STOCKS: Stock[] = [
  // Technology & E-commerce
  { symbol: 'BUKA.JK', name: 'Bukalapak.com Tbk', sector: 'Technology' },
  { symbol: 'DNET.JK', name: 'Indoritel Makmur Internasional Tbk', sector: 'Technology' },
  { symbol: 'WIFI.JK', name: 'Eka Mas Republik Tbk', sector: 'Technology' },
  
  // Banking & Finance
  { symbol: 'BTPS.JK', name: 'Bank BTPN Syariah Tbk', sector: 'Finance' },
  { symbol: 'BNGA.JK', name: 'Bank CIMB Niaga Tbk', sector: 'Finance' },
  { symbol: 'BDMN.JK', name: 'Bank Danamon Indonesia Tbk', sector: 'Finance' },
  { symbol: 'BJBR.JK', name: 'Bank Pembangunan Daerah Jawa Barat dan Banten Tbk', sector: 'Finance' },
  { symbol: 'MEGA.JK', name: 'Bank Mega Tbk', sector: 'Finance' },
  { symbol: 'BJTM.JK', name: 'Bank Pembangunan Daerah Jawa Timur Tbk', sector: 'Finance' },
  { symbol: 'NISP.JK', name: 'Bank OCBC NISP Tbk', sector: 'Finance' },
  { symbol: 'PNBN.JK', name: 'Bank Pan Indonesia Tbk', sector: 'Finance' },
  { symbol: 'BNLI.JK', name: 'Bank Permata Tbk', sector: 'Finance' },
  { symbol: 'BSIM.JK', name: 'Bank Sinarmas Tbk', sector: 'Finance' },
  { symbol: 'BBKP.JK', name: 'Bank KB Bukopin Tbk', sector: 'Finance' },
  { symbol: 'BBTN.JK', name: 'Bank Tabungan Negara Tbk', sector: 'Finance' },
  { symbol: 'BTPN.JK', name: 'Bank BTPN Tbk', sector: 'Finance' },
  { symbol: 'MAYA.JK', name: 'Bank Mayapada Internasional Tbk', sector: 'Finance' },
  { symbol: 'MCOR.JK', name: 'Bank China Construction Bank Indonesia Tbk', sector: 'Finance' },
  { symbol: 'BACA.JK', name: 'Bank Capital Indonesia Tbk', sector: 'Finance' },
  { symbol: 'AGRO.JK', name: 'Bank Rakyat Indonesia Agroniaga Tbk', sector: 'Finance' },
  { symbol: 'NOBU.JK', name: 'Bank Nationalnobu Tbk', sector: 'Finance' },
  { symbol: 'BABP.JK', name: 'Bank MNC Internasional Tbk', sector: 'Finance' },
  { symbol: 'ARTO.JK', name: 'Bank Jago Tbk', sector: 'Finance' },
  { symbol: 'BBYB.JK', name: 'Bank Neo Commerce Tbk', sector: 'Finance' },
  
  // Insurance & Multifinance
  { symbol: 'ASRI.JK', name: 'Alam Sutera Realty Tbk', sector: 'Finance' },
  { symbol: 'ADMF.JK', name: 'Adira Dinamika Multi Finance Tbk', sector: 'Finance' },
  { symbol: 'BBLD.JK', name: 'Buana Finance Tbk', sector: 'Finance' },
  { symbol: 'MFIN.JK', name: 'Mandala Multifinance Tbk', sector: 'Finance' },
  { symbol: 'PNLF.JK', name: 'Panin Financial Tbk', sector: 'Finance' },
  { symbol: 'WOMF.JK', name: 'Wahana Ottomitra Multiartha Tbk', sector: 'Finance' },
  { symbol: 'RAJA.JK', name: 'RAJA Tbk', sector: 'Finance' },
  
  // Energy & Mining
  { symbol: 'PGEO.JK', name: 'Pertamina Geothermal Energy Tbk', sector: 'Energy' },
  { symbol: 'ELSA.JK', name: 'Elnusa Tbk', sector: 'Energy' },
  { symbol: 'RUIS.JK', name: 'Radiant Utama Interinsco Tbk', sector: 'Energy' },
  { symbol: 'ENRG.JK', name: 'Energi Mega Persada Tbk', sector: 'Energy' },
  { symbol: 'DOID.JK', name: 'Delta Dunia Makmur Tbk', sector: 'Mining' },
  { symbol: 'TINS.JK', name: 'Timah Tbk', sector: 'Mining' },
  { symbol: 'INDY.JK', name: 'Indika Energy Tbk', sector: 'Mining' },
  { symbol: 'HRUM.JK', name: 'Harum Energy Tbk', sector: 'Mining' },
  { symbol: 'GEMS.JK', name: 'Golden Energy Mines Tbk', sector: 'Mining' },
  { symbol: 'MBAP.JK', name: 'Mitrabara Adiperdana Tbk', sector: 'Mining' },
  { symbol: 'KKGI.JK', name: 'Resource Alam Indonesia Tbk', sector: 'Mining' },
  { symbol: 'MDKA.JK', name: 'Merdeka Copper Gold Tbk', sector: 'Mining' },
  { symbol: 'MYOH.JK', name: 'Samindo Resources Tbk', sector: 'Mining' },
  { symbol: 'PKPK.JK', name: 'Perdana Karya Perkasa Tbk', sector: 'Mining' },
  { symbol: 'PTRO.JK', name: 'Petrosea Tbk', sector: 'Mining' },
  
  // Property & Real Estate
  { symbol: 'DMAS.JK', name: 'Puradelta Lestari Tbk', sector: 'Property' },
  { symbol: 'APLN.JK', name: 'Agung Podomoro Land Tbk', sector: 'Property' },
  { symbol: 'CTRA.JK', name: 'Ciputra Development Tbk', sector: 'Property' },
  { symbol: 'LPKR.JK', name: 'Lippo Karawaci Tbk', sector: 'Property' },
  { symbol: 'SMRA.JK', name: 'Summarecon Agung Tbk', sector: 'Property' },
  { symbol: 'BKSL.JK', name: 'Sentul City Tbk', sector: 'Property' },
  { symbol: 'PPRO.JK', name: 'PP Properti Tbk', sector: 'Property' },
  { symbol: 'EMDE.JK', name: 'Megapolitan Developments Tbk', sector: 'Property' },
  { symbol: 'GPRA.JK', name: 'Perdana Gapura Prima Tbk', sector: 'Property' },
  { symbol: 'KIJA.JK', name: 'Kawasan Industri Jababeka Tbk', sector: 'Property' },
  { symbol: 'MTLA.JK', name: 'Metropolitan Land Tbk', sector: 'Property' },
  { symbol: 'RDTX.JK', name: 'Roda Vivatex Tbk', sector: 'Property' },
  { symbol: 'PLIN.JK', name: 'Plaza Indonesia Realty Tbk', sector: 'Property' },
  { symbol: 'BEST.JK', name: 'Bekasi Fajar Industrial Estate Tbk', sector: 'Property' },
  { symbol: 'COWL.JK', name: 'Cowell Development Tbk', sector: 'Property' },
  { symbol: 'DART.JK', name: 'Duta Anggada Realty Tbk', sector: 'Property' },
  { symbol: 'DUTI.JK', name: 'Duta Pertiwi Tbk', sector: 'Property' },
  { symbol: 'MKPI.JK', name: 'Metropolitan Kentjana Tbk', sector: 'Property' },
  { symbol: 'PUDP.JK', name: 'Pudjiadi Prestige Tbk', sector: 'Property' },
  { symbol: 'SMDM.JK', name: 'Suryamas Dutamakmur Tbk', sector: 'Property' },
  { symbol: 'GWSA.JK', name: 'Greenwood Sejahtera Tbk', sector: 'Property' },
  
  // Consumer Goods & Retail
  { symbol: 'MYOR.JK', name: 'Mayora Indah Tbk', sector: 'Consumer Goods' },
  { symbol: 'ULTJ.JK', name: 'Ultra Jaya Milk Industry & Trading Company Tbk', sector: 'Consumer Goods' },
  { symbol: 'ROTI.JK', name: 'Nippon Indosari Corpindo Tbk', sector: 'Consumer Goods' },
  { symbol: 'DLTA.JK', name: 'Delta Djakarta Tbk', sector: 'Consumer Goods' },
  { symbol: 'SKLT.JK', name: 'Sekar Laut Tbk', sector: 'Consumer Goods' },
  { symbol: 'SKBM.JK', name: 'Sekar Bumi Tbk', sector: 'Consumer Goods' },
  { symbol: 'PSDN.JK', name: 'Prasidha Aneka Niaga Tbk', sector: 'Consumer Goods' },
  { symbol: 'CAMP.JK', name: 'Campina Ice Cream Industry Tbk', sector: 'Consumer Goods' },
  { symbol: 'GOOD.JK', name: 'Garudafood Putra Putri Jaya Tbk', sector: 'Consumer Goods' },
  { symbol: 'HOKI.JK', name: 'Buyung Poetra Sembada Tbk', sector: 'Consumer Goods' },
  { symbol: 'STTP.JK', name: 'Siantar Top Tbk', sector: 'Consumer Goods' },
  { symbol: 'AISA.JK', name: 'Tiga Pilar Sejahtera Food Tbk', sector: 'Consumer Goods' },
  { symbol: 'ADES.JK', name: 'Akasha Wira International Tbk', sector: 'Consumer Goods' },
  { symbol: 'MPPA.JK', name: 'Matahari Putra Prima Tbk', sector: 'Retail' },
  { symbol: 'LPPF.JK', name: 'Matahari Department Store Tbk', sector: 'Retail' },
  { symbol: 'HERO.JK', name: 'Hero Supermarket Tbk', sector: 'Retail' },
  { symbol: 'RALS.JK', name: 'Ramayana Lestari Sentosa Tbk', sector: 'Retail' },
  { symbol: 'AMRT.JK', name: 'Sumber Alfaria Trijaya Tbk', sector: 'Retail' },
  { symbol: 'CENT.JK', name: 'Centratama Telekomunikasi Indonesia Tbk', sector: 'Retail' },
  { symbol: 'KOIN.JK', name: 'Kokoh Inti Arebama Tbk', sector: 'Retail' },
  { symbol: 'RANC.JK', name: 'Supra Boga Lestari Tbk', sector: 'Retail' },
  { symbol: 'MIDI.JK', name: 'Midi Utama Indonesia Tbk', sector: 'Retail' },
  
  // Healthcare & Pharmaceutical
  { symbol: 'KAEF.JK', name: 'Kimia Farma Tbk', sector: 'Healthcare' },
  { symbol: 'INAF.JK', name: 'Indofarma Tbk', sector: 'Healthcare' },
  { symbol: 'DVLA.JK', name: 'Darya-Varia Laboratoria Tbk', sector: 'Healthcare' },
  { symbol: 'PYFA.JK', name: 'Pyridam Farma Tbk', sector: 'Healthcare' },
  { symbol: 'TSPC.JK', name: 'Tempo Scan Pacific Tbk', sector: 'Healthcare' },
  { symbol: 'MIKA.JK', name: 'Mitra Keluarga Karyasehat Tbk', sector: 'Healthcare' },
  { symbol: 'SILO.JK', name: 'Siloam International Hospitals Tbk', sector: 'Healthcare' },
  { symbol: 'HEAL.JK', name: 'Medikaloka Hermina Tbk', sector: 'Healthcare' },
  { symbol: 'SAME.JK', name: 'Sarana Meditama Metropolitan Tbk', sector: 'Healthcare' },
  { symbol: 'PRDA.JK', name: 'Prodia Widyahusada Tbk', sector: 'Healthcare' },
  { symbol: 'SRAJ.JK', name: 'Sejahteraraya Anugrahjaya Tbk', sector: 'Healthcare' },
  { symbol: 'PRIM.JK', name: 'Primier Bintang Resources Tbk', sector: 'Healthcare' },
  
  // Telecommunication & Media
  { symbol: 'ISAT.JK', name: 'Indosat Ooredoo Hutchison Tbk', sector: 'Telecommunication' },
  { symbol: 'FREN.JK', name: 'Smartfren Telecom Tbk', sector: 'Telecommunication' },
  { symbol: 'LINK.JK', name: 'Link Net Tbk', sector: 'Telecommunication' },
  { symbol: 'BCIP.JK', name: 'Bumi Citra Permai Tbk', sector: 'Telecommunication' },
  { symbol: 'FILM.JK', name: 'MD Pictures Tbk', sector: 'Media' },
  { symbol: 'VIVA.JK', name: 'Visi Media Asia Tbk', sector: 'Media' },
  { symbol: 'ABBA.JK', name: 'Mahaka Media Tbk', sector: 'Media' },
  { symbol: 'KBLV.JK', name: 'First Media Tbk', sector: 'Media' },
  { symbol: 'BMTR.JK', name: 'Global Mediacom Tbk', sector: 'Media' },
  { symbol: 'TFCO.JK', name: 'Tifico Fiber Indonesia Tbk', sector: 'Telecommunication' },
  { symbol: 'PTSN.JK', name: 'Sat Nusapersada Tbk', sector: 'Telecommunication' },
  
  // Manufacturing & Industrial
  { symbol: 'WOOD.JK', name: 'Integra Indocabinet Tbk', sector: 'Manufacturing' },
  { symbol: 'SRSN.JK', name: 'Indo Acidatama Tbk', sector: 'Manufacturing' },
  { symbol: 'ARNA.JK', name: 'Arwana Citramulia Tbk', sector: 'Manufacturing' },
  { symbol: 'TOTO.JK', name: 'Surya Toto Indonesia Tbk', sector: 'Manufacturing' },
  { symbol: 'ALMI.JK', name: 'Alumindo Light Metal Industry Tbk', sector: 'Manufacturing' },
  { symbol: 'ALKA.JK', name: 'Alaska Industrindo Tbk', sector: 'Manufacturing' },
  { symbol: 'LION.JK', name: 'Lion Metal Works Tbk', sector: 'Manufacturing' },
  { symbol: 'LMSH.JK', name: 'Lionmesh Prima Tbk', sector: 'Manufacturing' },
  { symbol: 'BTON.JK', name: 'Betonjaya Manunggal Tbk', sector: 'Manufacturing' },
  { symbol: 'IMPC.JK', name: 'Impack Pratama Industri Tbk', sector: 'Manufacturing' },
  { symbol: 'TRST.JK', name: 'Trias Sentosa Tbk', sector: 'Manufacturing' },
  { symbol: 'MBTO.JK', name: 'Martina Berto Tbk', sector: 'Manufacturing' },
  { symbol: 'TCID.JK', name: 'Mandom Indonesia Tbk', sector: 'Manufacturing' },
  { symbol: 'KBLI.JK', name: 'KMI Wire and Cable Tbk', sector: 'Manufacturing' },
  { symbol: 'KBLM.JK', name: 'Kabelindo Murni Tbk', sector: 'Manufacturing' },
  { symbol: 'JECC.JK', name: 'Jembo Cable Company Tbk', sector: 'Manufacturing' },
  { symbol: 'VOKS.JK', name: 'Voksel Electric Tbk', sector: 'Manufacturing' },
  { symbol: 'GDST.JK', name: 'Gunawan Dianjaya Steel Tbk', sector: 'Manufacturing' },
  { symbol: 'INDS.JK', name: 'Indospring Tbk', sector: 'Manufacturing' },
  { symbol: 'PICO.JK', name: 'Pelangi Indah Canindo Tbk', sector: 'Manufacturing' },
  { symbol: 'FASW.JK', name: 'Fajar Surya Wisesa Tbk', sector: 'Manufacturing' },
  { symbol: 'SPMA.JK', name: 'Suparma Tbk', sector: 'Manufacturing' },
  { symbol: 'ALDO.JK', name: 'Alkindo Naratama Tbk', sector: 'Manufacturing' },
  
  // Automotive & Components
  { symbol: 'AUTO.JK', name: 'Astra Otoparts Tbk', sector: 'Automotive' },
  { symbol: 'SMSM.JK', name: 'Selamat Sempurna Tbk', sector: 'Automotive' },
  { symbol: 'GJTL.JK', name: 'Gajah Tunggal Tbk', sector: 'Automotive' },
  { symbol: 'IMAS.JK', name: 'Indomobil Sukses Internasional Tbk', sector: 'Automotive' },
  { symbol: 'NIPS.JK', name: 'Nipress Tbk', sector: 'Automotive' },
  { symbol: 'PRAS.JK', name: 'Prima Alloy Steel Universal Tbk', sector: 'Automotive' },
  { symbol: 'LPIN.JK', name: 'Multi Prima Sejahtera Tbk', sector: 'Automotive' },
  { symbol: 'BOLT.JK', name: 'Garuda Metalindo Tbk', sector: 'Automotive' },
  { symbol: 'GDYR.JK', name: 'Goodyear Indonesia Tbk', sector: 'Automotive' },
  { symbol: 'MASA.JK', name: 'Multistrada Arah Sarana Tbk', sector: 'Automotive' },
  { symbol: 'PRIMA.JK', name: 'Prima Alloy Steel Universal Tbk', sector: 'Automotive' },
  { symbol: 'INDR.JK', name: 'Indo-Rama Synthetics Tbk', sector: 'Automotive' },
  
  // Agriculture & Plantation
  { symbol: 'AALI.JK', name: 'Astra Agro Lestari Tbk', sector: 'Agriculture' },
  { symbol: 'LSIP.JK', name: 'PP London Sumatra Indonesia Tbk', sector: 'Agriculture' },
  { symbol: 'SGRO.JK', name: 'Sampoerna Agro Tbk', sector: 'Agriculture' },
  { symbol: 'SIMP.JK', name: 'Salim Ivomas Pratama Tbk', sector: 'Agriculture' },
  { symbol: 'TBLA.JK', name: 'Tunas Baru Lampung Tbk', sector: 'Agriculture' },
  { symbol: 'SSMS.JK', name: 'Sawit Sumbermas Sarana Tbk', sector: 'Agriculture' },
  { symbol: 'PALM.JK', name: 'Provident Agro Tbk', sector: 'Agriculture' },
  { symbol: 'ANJT.JK', name: 'Austindo Nusantara Jaya Tbk', sector: 'Agriculture' },
  { symbol: 'BWPT.JK', name: 'Eagle High Plantations Tbk', sector: 'Agriculture' },
  { symbol: 'DSNG.JK', name: 'Dharma Satya Nusantara Tbk', sector: 'Agriculture' },
  { symbol: 'GOLL.JK', name: 'Golden Plantation Tbk', sector: 'Agriculture' },
  { symbol: 'MGRO.JK', name: 'Mahkota Group Tbk', sector: 'Agriculture' },
  { symbol: 'TAPG.JK', name: 'Triputra Agro Persada Tbk', sector: 'Agriculture' },
  { symbol: 'UNSP.JK', name: 'Bakrie Sumatera Plantations Tbk', sector: 'Agriculture' },
  { symbol: 'JAWA.JK', name: 'Jaya Agra Wattie Tbk', sector: 'Agriculture' },
  { symbol: 'BTEK.JK', name: 'Bumi Teknokultura Unggul Tbk', sector: 'Agriculture' },
  
  // Transportation & Logistics
  { symbol: 'BIRD.JK', name: 'Blue Bird Tbk', sector: 'Transportation' },
  { symbol: 'TRAM.JK', name: 'Trada Maritime Tbk', sector: 'Transportation' },
  { symbol: 'WEHA.JK', name: 'Panorama Transportasi Tbk', sector: 'Transportation' },
  { symbol: 'CMPP.JK', name: 'AirAsia Indonesia Tbk', sector: 'Transportation' },
  { symbol: 'GIAA.JK', name: 'Garuda Indonesia Tbk', sector: 'Transportation' },
  { symbol: 'SMDR.JK', name: 'Samudera Indonesia Tbk', sector: 'Transportation' },
  { symbol: 'TMAS.JK', name: 'Pelayaran Tempuran Emas Tbk', sector: 'Transportation' },
  { symbol: 'ASSA.JK', name: 'Adi Sarana Armada Tbk', sector: 'Transportation' },
  { symbol: 'TAXI.JK', name: 'Express Transindo Utama Tbk', sector: 'Transportation' },
  { symbol: 'KARW.JK', name: 'ICTSI Jasa Prima Tbk', sector: 'Transportation' },
  { symbol: 'NELY.JK', name: 'Pelayaran Nelly Dwi Putri Tbk', sector: 'Transportation' },
  { symbol: 'PTIS.JK', name: 'Indo Straits Tbk', sector: 'Transportation' },
  { symbol: 'APOL.JK', name: 'Arpeni Pratama Ocean Line Tbk', sector: 'Transportation' },
  
  // Construction & Infrastructure
  { symbol: 'ADHI.JK', name: 'Adhi Karya Tbk', sector: 'Construction' },
  { symbol: 'TOTL.JK', name: 'Total Bangun Persada Tbk', sector: 'Construction' },
  { symbol: 'NRCA.JK', name: 'Nusa Raya Cipta Tbk', sector: 'Construction' },
  { symbol: 'DGIK.JK', name: 'Nusa Konstruksi Enjiniring Tbk', sector: 'Construction' },
  { symbol: 'ACST.JK', name: 'Acset Indonusa Tbk', sector: 'Construction' },
  { symbol: 'SSIA.JK', name: 'Surya Semesta Internusa Tbk', sector: 'Construction' },
  { symbol: 'IDPR.JK', name: 'Indonesia Pondasi Raya Tbk', sector: 'Construction' },
  { symbol: 'CSIS.JK', name: 'Cahayasakti Investindo Sukses Tbk', sector: 'Construction' },
  { symbol: 'AGRS.JK', name: 'Bank Agris Tbk', sector: 'Construction' },
  { symbol: 'PBSA.JK', name: 'Paramita Bangun Sarana Tbk', sector: 'Construction' },
  
  // Chemical & Basic Industry
  { symbol: 'TKIM.JK', name: 'Pabrik Kertas Tjiwi Kimia Tbk', sector: 'Chemical' },
  { symbol: 'FPNI.JK', name: 'Lotte Chemical Titan Tbk', sector: 'Chemical' },
  { symbol: 'AKPI.JK', name: 'Argha Karya Prima Industry Tbk', sector: 'Chemical' },
  { symbol: 'EKAD.JK', name: 'Ekadharma International Tbk', sector: 'Chemical' },
  { symbol: 'DPNS.JK', name: 'Duta Pertiwi Nusantara Tbk', sector: 'Chemical' },
  { symbol: 'BUDI.JK', name: 'Budi Starch & Sweetener Tbk', sector: 'Chemical' },
  { symbol: 'CEKA.JK', name: 'Wilmar Cahaya Indonesia Tbk', sector: 'Chemical' },
  { symbol: 'UNIC.JK', name: 'Unggul Indah Cahaya Tbk', sector: 'Chemical' },
  { symbol: 'ETWA.JK', name: 'Eterindo Wahanatama Tbk', sector: 'Chemical' },
  { symbol: 'INCI.JK', name: 'Intanwijaya Internasional Tbk', sector: 'Chemical' },
  { symbol: 'SULI.JK', name: 'Sumalindo Lestari Jaya Tbk', sector: 'Chemical' },
  
  // Textile & Garment
  { symbol: 'SSTM.JK', name: 'Sunson Textile Manufacturer Tbk', sector: 'Textile' },
  { symbol: 'PBRX.JK', name: 'Pan Brothers Tbk', sector: 'Textile' },
  { symbol: 'MYTX.JK', name: 'Asia Pacific Investama Tbk', sector: 'Textile' },
  { symbol: 'POLY.JK', name: 'Asia Pacific Fibers Tbk', sector: 'Textile' },
  { symbol: 'ARGO.JK', name: 'Argo Pantes Tbk', sector: 'Textile' },
  { symbol: 'ADMG.JK', name: 'Polychem Indonesia Tbk', sector: 'Textile' },
  { symbol: 'UNIT.JK', name: 'Nusantara Inti Corpora Tbk', sector: 'Textile' },
  { symbol: 'ERTX.JK', name: 'Eratex Djaya Tbk', sector: 'Textile' },
  { symbol: 'HDTX.JK', name: 'Panasia Indo Resources Tbk', sector: 'Textile' },
  { symbol: 'BELL.JK', name: 'Trisula Textile Industries Tbk', sector: 'Textile' },
  { symbol: 'CNTX.JK', name: 'Century Textile Industry Tbk', sector: 'Textile' },
  { symbol: 'ESTI.JK', name: 'Ever Shine Tex Tbk', sector: 'Textile' },
  { symbol: 'TRIS.JK', name: 'Trisula International Tbk', sector: 'Textile' },
  
  // Tourism & Hotel
  { symbol: 'PNSE.JK', name: 'Pudjiadi And Sons Tbk', sector: 'Tourism' },
  { symbol: 'PANR.JK', name: 'Panorama Sentrawisata Tbk', sector: 'Tourism' },
  { symbol: 'BAYU.JK', name: 'Bayu Buana Tbk', sector: 'Tourism' },
  { symbol: 'SHID.JK', name: 'Hotel Sahid Jaya International Tbk', sector: 'Tourism' },
  { symbol: 'PDES.JK', name: 'Destinasi Tirta Nusantara Tbk', sector: 'Tourism' },
  { symbol: 'JIHD.JK', name: 'Jakarta International Hotels & Development Tbk', sector: 'Tourism' },
  { symbol: 'PSKT.JK', name: 'Red Planet Indonesia Tbk', sector: 'Tourism' },
  { symbol: 'MABA.JK', name: 'Makmur Berkah Amanda Tbk', sector: 'Tourism' },
  { symbol: 'HOTL.JK', name: 'Saraswanti Indo Genetech Tbk', sector: 'Tourism' },
  
  // Trade & Services
  { symbol: 'MSIN.JK', name: 'MNC Studios International Tbk', sector: 'Trade' },
  { symbol: 'SCPI.JK', name: 'Organon Pharma Indonesia Tbk', sector: 'Trade' },
  { symbol: 'CSAP.JK', name: 'Catur Sentosa Adiprana Tbk', sector: 'Trade' },
  { symbol: 'RICY.JK', name: 'Ricky Putra Globalindo Tbk', sector: 'Trade' },
  { symbol: 'TELE.JK', name: 'Tiphone Mobile Indonesia Tbk', sector: 'Trade' },
  { symbol: 'GLOB.JK', name: 'Global Teleshop Tbk', sector: 'Trade' },
  { symbol: 'MICE.JK', name: 'Multi Indocitra Tbk', sector: 'Trade' },
  { symbol: 'INTD.JK', name: 'Inter Delta Tbk', sector: 'Trade' },
  { symbol: 'CNKO.JK', name: 'Exploitasi Energi Indonesia Tbk', sector: 'Trade' },
  
  // Investment & Holding
  { symbol: 'BFIN.JK', name: 'BFI Finance Indonesia Tbk', sector: 'Investment' },
  { symbol: 'PANS.JK', name: 'Panin Sekuritas Tbk', sector: 'Investment' },
  { symbol: 'TRIM.JK', name: 'Trimegah Sekuritas Indonesia Tbk', sector: 'Investment' },
  { symbol: 'PEGE.JK', name: 'Panca Global Securities Tbk', sector: 'Investment' },
  { symbol: 'YULE.JK', name: 'Yulie Sekurindo Tbk', sector: 'Investment' },
  { symbol: 'KREN.JK', name: 'Kresna Graha Investama Tbk', sector: 'Investment' },
  { symbol: 'HADE.JK', name: 'HD Capital Tbk', sector: 'Investment' },
  { symbol: 'LPPS.JK', name: 'Lippo Securities Tbk', sector: 'Investment' },
  { symbol: 'OCAP.JK', name: 'Onix Capital Tbk', sector: 'Investment' },
  { symbol: 'BBHI.JK', name: 'Allo Bank Indonesia Tbk', sector: 'Finance' },
  { symbol: 'BMAS.JK', name: 'Bank Maspion Indonesia Tbk', sector: 'Finance' },
  { symbol: 'BSBK.JK', name: 'Bank Saudara Tbk', sector: 'Finance' },
  { symbol: 'BVIC.JK', name: 'Bank Victoria International Tbk', sector: 'Finance' },
  { symbol: 'DNAR.JK', name: 'Bank Dinar Indonesia Tbk', sector: 'Finance' },
  { symbol: 'PNBS.JK', name: 'Bank Pan Indonesia Syariah Tbk', sector: 'Finance' },
];

export const ALL_STOCKS = [...LQ45_STOCKS, ...OTHER_STOCKS];