import { Stock } from '@/types/stock';

export const LQ45_STOCKS: Stock[] = [
  { symbol: 'BBCA.JK', name: 'Bank Central Asia Tbk', sector: 'Finance' },
  { symbol: 'BBRI.JK', name: 'Bank Rakyat Indonesia Tbk', sector: 'Finance' },
  { symbol: 'BMRI.JK', name: 'Bank Mandiri Tbk', sector: 'Finance' },
  { symbol: 'BBNI.JK', name: 'Bank Negara Indonesia Tbk', sector: 'Finance' },
  { symbol: 'TLKM.JK', name: 'Telkom Indonesia Tbk', sector: 'Telecommunication' },
  { symbol: 'ASII.JK', name: 'Astra International Tbk', sector: 'Automotive' },
  { symbol: 'UNVR.JK', name: 'Unilever Indonesia Tbk', sector: 'Consumer Goods' },
  { symbol: 'GOTO.JK', name: 'GoTo Gojek Tokopedia Tbk', sector: 'Technology' },
  { symbol: 'AMMN.JK', name: 'Amman Mineral Internasional Tbk', sector: 'Mining' },
  { symbol: 'ANTM.JK', name: 'Aneka Tambang Tbk', sector: 'Mining' },
  { symbol: 'INDF.JK', name: 'Indofood Sukses Makmur Tbk', sector: 'Consumer Goods' },
  { symbol: 'ICBP.JK', name: 'Indofood CBP Sukses Makmur Tbk', sector: 'Consumer Goods' },
  { symbol: 'KLBF.JK', name: 'Kalbe Farma Tbk', sector: 'Healthcare' },
  { symbol: 'EMTK.JK', name: 'Elang Mahkota Teknologi Tbk', sector: 'Media' },
  { symbol: 'ADRO.JK', name: 'Adaro Energy Indonesia Tbk', sector: 'Mining' },
  { symbol: 'PTBA.JK', name: 'Bukit Asam Tbk', sector: 'Mining' },
  { symbol: 'INKP.JK', name: 'Indah Kiat Pulp & Paper Tbk', sector: 'Manufacturing' },
  { symbol: 'SMGR.JK', name: 'Semen Indonesia Tbk', sector: 'Construction' },
  { symbol: 'INTP.JK', name: 'Indocement Tunggal Prakarsa Tbk', sector: 'Construction' },
  { symbol: 'GGRM.JK', name: 'Gudang Garam Tbk', sector: 'Consumer Goods' },
  { symbol: 'HMSP.JK', name: 'HM Sampoerna Tbk', sector: 'Consumer Goods' },
  { symbol: 'BRIS.JK', name: 'Bank BRI Syariah Tbk', sector: 'Finance' },
  { symbol: 'EXCL.JK', name: 'XL Axiata Tbk', sector: 'Telecommunication' },
  { symbol: 'PGAS.JK', name: 'Perusahaan Gas Negara Tbk', sector: 'Energy' },
  { symbol: 'PWON.JK', name: 'Pakuwon Jati Tbk', sector: 'Property' },
  { symbol: 'MNCN.JK', name: 'Media Nusantara Citra Tbk', sector: 'Media' },
  { symbol: 'AKRA.JK', name: 'AKR Corporindo Tbk', sector: 'Trade' },
  { symbol: 'CPIN.JK', name: 'Charoen Pokphand Indonesia Tbk', sector: 'Agriculture' },
  { symbol: 'BRPT.JK', name: 'Barito Pacific Tbk', sector: 'Chemical' },
  { symbol: 'ITMG.JK', name: 'Indo Tambangraya Megah Tbk', sector: 'Mining' },
  { symbol: 'MEDC.JK', name: 'Medco Energi Internasional Tbk', sector: 'Energy' },
  { symbol: 'SCMA.JK', name: 'Surya Citra Media Tbk', sector: 'Media' },
  { symbol: 'MAPI.JK', name: 'Mitra Adiperkasa Tbk', sector: 'Retail' },
  { symbol: 'JSMR.JK', name: 'Jasa Marga Tbk', sector: 'Infrastructure' },
  { symbol: 'WIKA.JK', name: 'Wijaya Karya Tbk', sector: 'Construction' },
  { symbol: 'WSKT.JK', name: 'Waskita Karya Tbk', sector: 'Construction' },
  { symbol: 'PTPP.JK', name: 'PP Tbk', sector: 'Construction' },
  { symbol: 'TPIA.JK', name: 'Chandra Asri Pacific Tbk', sector: 'Chemical' },
  { symbol: 'UNTR.JK', name: 'United Tractors Tbk', sector: 'Automotive' },
  { symbol: 'TOWR.JK', name: 'Sarana Menara Nusantara Tbk', sector: 'Telecommunication' },
  { symbol: 'ERAA.JK', name: 'Erajaya Swasembada Tbk', sector: 'Retail' },
  { symbol: 'BSDE.JK', name: 'Bumi Serpong Damai Tbk', sector: 'Property' },
  { symbol: 'JPFA.JK', name: 'Japfa Comfeed Indonesia Tbk', sector: 'Agriculture' },
  { symbol: 'ACES.JK', name: 'Ace Hardware Indonesia Tbk', sector: 'Retail' },
  { symbol: 'SIDO.JK', name: 'Industri Jamu Dan Farmasi Sido Muncul Tbk', sector: 'Healthcare' },
];

export const OTHER_STOCKS: Stock[] = [
  { symbol: 'BUKA.JK', name: 'Bukalapak.com Tbk', sector: 'Technology' },
  { symbol: 'PGEO.JK', name: 'Pertamina Geothermal Energy Tbk', sector: 'Energy' },
  { symbol: 'DMAS.JK', name: 'Puradelta Lestari Tbk', sector: 'Property' },
  { symbol: 'WOOD.JK', name: 'Integra Indocabinet Tbk', sector: 'Manufacturing' },
  { symbol: 'FILM.JK', name: 'MD Pictures Tbk', sector: 'Media' },
];

export const ALL_STOCKS = [...LQ45_STOCKS, ...OTHER_STOCKS];